# Generated by Django 6.1 on 2026-09-06 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.department'),
        ),
    ]
